[package]
name = "wlt_task"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
encoding_rs = "0.8.33"
lettre = "0.10.4"
reqwest = { version = "0.11.20", features = ["blocking", "cookies"] }
reqwest_cookie_store = "0.6.0"
scraper = "0.17.1"
serde = { version = "1.0.188", features = ["derive"] }
toml = "0.8.0"
urlencoding = "2.1.3"
